fetch('https://jsonplaceholder.typicodeasd.com/posts/1')
.then(response => response.text())
// .catch(() => {console.log('에러가 발생되었습니다.')})
.then(()=>{console.log(a)})
.catch(() => {console.log('에러가 발생되었습니다.')})
.finally(() =>{console.log('작업이 마감되었습니다.')})